spring:
  application:
    name: to-do-app
  datasource:
    url: # moved to vault
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: todo
        format_sql: true
  flyway:
    baseline-on-migrate: true
    default-schema: todo
  config:
    import: vault://secret/to-do-app/local
  cloud:
    vault:
      uri: ${VAULT_ADDR:http://localhost:8200}
      fail-fast: true
      scheme: http

springdoc:
  api-docs:
    version: openapi_3_0
  paths-to-match: /api/**
  writer-with-default-pretty-printer: true


jwt:
  issuer: ${spring.application.name}
  private-key: classpath:keystore.key
  public-key: classpath:keystore.pub
  ttl: 1h

logging:
  level:
    com.project.todo: DEBUG